apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kellar-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: kellar-core
  endpoints:
  - port: http
    interval: 15s
