plugins {
    id 'com.android.application'
}

android {
    namespace 'com.darnellwashingtonjr94_art.edge'
    compileSdk 34

    defaultConfig {
        applicationId "com.darnellwashingtonjr94_art.edge"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

     buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
